# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dash.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModernDashboard(object):
    def setupUi(self, ModernDashboard):
        ModernDashboard.setObjectName("ModernDashboard")
        ModernDashboard.resize(1015, 880)
        ModernDashboard.setMinimumSize(QtCore.QSize(880, 880))
        ModernDashboard.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(ModernDashboard)
        self.centralwidget.setObjectName("centralwidget")
        self.main_layout = QtWidgets.QGridLayout(self.centralwidget)
        self.main_layout.setObjectName("main_layout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setStyleSheet("\n"
"        QGroupBox {\n"
"            border: 2px solid #9C27B0;\n"
"            border-radius: 10px;\n"
"            margin-top: 10px;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 0 5px 0 5px;\n"
"            font-weight: bold;\n"
"            color: #9C27B0;\n"
"        }\n"
"\n"
"QCheckBox {\n"
"    spacing: 8px; /* Espacio entre la caja y el texto */\n"
"    font-size: 8px;\n"
"    color: #2c3e50;\n"
"    padding: 5px;\n"
"    font-family: \'Arial\', sans-serif;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    border-radius: 4px;\n"
"    background-color: #bdc3c7;\n"
"    border: 1px solid #95a5a6;\n"
"    transition: all 0.3s ease;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #95a5a6;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: #3498db;\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"QCheckBox::indicator:unchecked:hover {\n"
"    border: 1px solid #3498db;\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: #2980b9;\n"
"    border: 1px solid #2980b9;\n"
"}\n"
"\n"
"QCheckBox::indicator:disabled {\n"
"    background-color: #e0e0e0;\n"
"    border: 1px solid #bdc3c7;\n"
"    opacity: 0.5;\n"
"}\n"
"")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.bombilla_1 = QtWidgets.QCheckBox(self.groupBox)
        self.bombilla_1.setObjectName("bombilla_1")
        self.gridLayout.addWidget(self.bombilla_1, 0, 2, 1, 1)
        self.cpu_usage = QtWidgets.QLabel(self.groupBox)
        self.cpu_usage.setObjectName("cpu_usage")
        self.gridLayout.addWidget(self.cpu_usage, 1, 0, 1, 1)
        self.bombilla_2 = QtWidgets.QCheckBox(self.groupBox)
        self.bombilla_2.setObjectName("bombilla_2")
        self.gridLayout.addWidget(self.bombilla_2, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.purificador = QtWidgets.QCheckBox(self.groupBox)
        self.purificador.setObjectName("purificador")
        self.gridLayout.addWidget(self.purificador, 5, 2, 1, 1)
        self.bombilla_4 = QtWidgets.QCheckBox(self.groupBox)
        self.bombilla_4.setObjectName("bombilla_4")
        self.gridLayout.addWidget(self.bombilla_4, 3, 2, 1, 1)
        self.bombilla_3 = QtWidgets.QCheckBox(self.groupBox)
        self.bombilla_3.setObjectName("bombilla_3")
        self.gridLayout.addWidget(self.bombilla_3, 2, 2, 1, 1)
        self.deshumificador = QtWidgets.QCheckBox(self.groupBox)
        self.deshumificador.setObjectName("deshumificador")
        self.gridLayout.addWidget(self.deshumificador, 7, 2, 1, 1)
        self.abanico = QtWidgets.QCheckBox(self.groupBox)
        self.abanico.setObjectName("abanico")
        self.gridLayout.addWidget(self.abanico, 8, 2, 1, 1)
        self.ram_usage = QtWidgets.QLabel(self.groupBox)
        self.ram_usage.setObjectName("ram_usage")
        self.gridLayout.addWidget(self.ram_usage, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.clock_status = QtWidgets.QLabel(self.groupBox)
        self.clock_status.setStyleSheet("color: red;")
        self.clock_status.setObjectName("clock_status")
        self.gridLayout.addWidget(self.clock_status, 7, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.esp_01_status = QtWidgets.QLabel(self.groupBox)
        self.esp_01_status.setStyleSheet("color: red;")
        self.esp_01_status.setObjectName("esp_01_status")
        self.gridLayout_2.addWidget(self.esp_01_status, 1, 0, 1, 1)
        self.esp_02_status = QtWidgets.QLabel(self.groupBox)
        self.esp_02_status.setStyleSheet("color: red;")
        self.esp_02_status.setObjectName("esp_02_status")
        self.gridLayout_2.addWidget(self.esp_02_status, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 8, 0, 1, 1)
        self.main_layout.addWidget(self.groupBox, 2, 1, 1, 1)
        self.camera_group = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.camera_group.sizePolicy().hasHeightForWidth())
        self.camera_group.setSizePolicy(sizePolicy)
        self.camera_group.setObjectName("camera_group")
        self.camera_layout = QtWidgets.QHBoxLayout(self.camera_group)
        self.camera_layout.setContentsMargins(0, 0, 0, 9)
        self.camera_layout.setObjectName("camera_layout")
        self.cam_frame_1 = QtWidgets.QFrame(self.camera_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam_frame_1.sizePolicy().hasHeightForWidth())
        self.cam_frame_1.setSizePolicy(sizePolicy)
        self.cam_frame_1.setMinimumSize(QtCore.QSize(0, 0))
        self.cam_frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cam_frame_1.setObjectName("cam_frame_1")
        self.cam_layout_1 = QtWidgets.QVBoxLayout(self.cam_frame_1)
        self.cam_layout_1.setObjectName("cam_layout_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.cam_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox_camera1 = QtWidgets.QComboBox(self.cam_frame_1)
        self.comboBox_camera1.setStyleSheet("    QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        min-width: 100px;\n"
"        font-size: 14px;\n"
"        color: #333333;\n"
"        background-color: #f0f0f0;\n"
"    }")
        self.comboBox_camera1.setObjectName("comboBox_camera1")
        self.horizontalLayout_2.addWidget(self.comboBox_camera1)
        self.cam_layout_1.addLayout(self.horizontalLayout_2)
        self.cam_label_1 = QtWidgets.QLabel(self.cam_frame_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cam_label_1.setFont(font)
        self.cam_label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_label_1.setObjectName("cam_label_1")
        self.cam_layout_1.addWidget(self.cam_label_1)
        self.cam_view_1 = QtWidgets.QWidget(self.cam_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam_view_1.sizePolicy().hasHeightForWidth())
        self.cam_view_1.setSizePolicy(sizePolicy)
        self.cam_view_1.setMinimumSize(QtCore.QSize(0, 0))
        self.cam_view_1.setObjectName("cam_view_1")
        self.cam_layout_1.addWidget(self.cam_view_1)
        self.camera_layout.addWidget(self.cam_frame_1)
        self.cam_frame_2 = QtWidgets.QFrame(self.camera_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam_frame_2.sizePolicy().hasHeightForWidth())
        self.cam_frame_2.setSizePolicy(sizePolicy)
        self.cam_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cam_frame_2.setObjectName("cam_frame_2")
        self.cam_layout_2 = QtWidgets.QVBoxLayout(self.cam_frame_2)
        self.cam_layout_2.setObjectName("cam_layout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.cam_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.comboBox_2_camera_2 = QtWidgets.QComboBox(self.cam_frame_2)
        self.comboBox_2_camera_2.setStyleSheet("    QComboBox {\n"
"        border: 1px solid gray;\n"
"        border-radius: 5px;\n"
"        padding: 5px;\n"
"        min-width: 100px;\n"
"        font-size: 14px;\n"
"        color: #333333;\n"
"        background-color: #f0f0f0;\n"
"    }")
        self.comboBox_2_camera_2.setObjectName("comboBox_2_camera_2")
        self.horizontalLayout_3.addWidget(self.comboBox_2_camera_2)
        self.cam_layout_2.addLayout(self.horizontalLayout_3)
        self.cam_label_2 = QtWidgets.QLabel(self.cam_frame_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.cam_label_2.setFont(font)
        self.cam_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cam_label_2.setObjectName("cam_label_2")
        self.cam_layout_2.addWidget(self.cam_label_2)
        self.cam_view_2 = QtWidgets.QWidget(self.cam_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cam_view_2.sizePolicy().hasHeightForWidth())
        self.cam_view_2.setSizePolicy(sizePolicy)
        self.cam_view_2.setMinimumSize(QtCore.QSize(0, 0))
        self.cam_view_2.setObjectName("cam_view_2")
        self.cam_layout_2.addWidget(self.cam_view_2)
        self.camera_layout.addWidget(self.cam_frame_2)
        self.main_layout.addWidget(self.camera_group, 0, 0, 1, 2)
        self.alert_group = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alert_group.sizePolicy().hasHeightForWidth())
        self.alert_group.setSizePolicy(sizePolicy)
        self.alert_group.setObjectName("alert_group")
        self.alert_layout = QtWidgets.QVBoxLayout(self.alert_group)
        self.alert_layout.setObjectName("alert_layout")
        self.alert_list = QtWidgets.QLabel(self.alert_group)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.alert_list.setFont(font)
        self.alert_list.setAlignment(QtCore.Qt.AlignTop)
        self.alert_list.setObjectName("alert_list")
        self.alert_layout.addWidget(self.alert_list)
        self.main_layout.addWidget(self.alert_group, 1, 1, 1, 1)
        self.sensor_group = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sensor_group.sizePolicy().hasHeightForWidth())
        self.sensor_group.setSizePolicy(sizePolicy)
        self.sensor_group.setMinimumSize(QtCore.QSize(0, 0))
        self.sensor_group.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sensor_group.setStyleSheet("        QGroupBox {\n"
"            border: 2px solid #2196F3;\n"
"            border-radius: 10px;\n"
"            margin-top: 10px;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 5px;\n"
"            font-weight: bold;\n"
"            color: #2196F3;\n"
"        }")
        self.sensor_group.setObjectName("sensor_group")
        self.sensor_layout = QtWidgets.QGridLayout(self.sensor_group)
        self.sensor_layout.setObjectName("sensor_layout")
        self.system_frame = QtWidgets.QFrame(self.sensor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system_frame.sizePolicy().hasHeightForWidth())
        self.system_frame.setSizePolicy(sizePolicy)
        self.system_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.system_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.system_frame.setObjectName("system_frame")
        self.movement_layout = QtWidgets.QVBoxLayout(self.system_frame)
        self.movement_layout.setObjectName("movement_layout")
        self.label11 = QtWidgets.QLabel(self.system_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label11.setFont(font)
        self.label11.setAlignment(QtCore.Qt.AlignCenter)
        self.label11.setObjectName("label11")
        self.movement_layout.addWidget(self.label11)
        self.system_label = QtWidgets.QLabel(self.system_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.system_label.setFont(font)
        self.system_label.setAlignment(QtCore.Qt.AlignCenter)
        self.system_label.setObjectName("system_label")
        self.movement_layout.addWidget(self.system_label)
        self.sensor_layout.addWidget(self.system_frame, 1, 1, 1, 1)
        self.heart_rate_frame = QtWidgets.QFrame(self.sensor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heart_rate_frame.sizePolicy().hasHeightForWidth())
        self.heart_rate_frame.setSizePolicy(sizePolicy)
        self.heart_rate_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.heart_rate_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.heart_rate_frame.setObjectName("heart_rate_frame")
        self.heart_rate_layout = QtWidgets.QVBoxLayout(self.heart_rate_frame)
        self.heart_rate_layout.setObjectName("heart_rate_layout")
        self.heart_rate_label = QtWidgets.QLabel(self.heart_rate_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.heart_rate_label.setFont(font)
        self.heart_rate_label.setAlignment(QtCore.Qt.AlignCenter)
        self.heart_rate_label.setObjectName("heart_rate_label")
        self.heart_rate_layout.addWidget(self.heart_rate_label)
        self.heart_rate_value = QtWidgets.QLabel(self.heart_rate_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.heart_rate_value.setFont(font)
        self.heart_rate_value.setAlignment(QtCore.Qt.AlignCenter)
        self.heart_rate_value.setObjectName("heart_rate_value")
        self.heart_rate_layout.addWidget(self.heart_rate_value)
        self.sensor_layout.addWidget(self.heart_rate_frame, 0, 0, 1, 1)
        self.body_temp_frame = QtWidgets.QFrame(self.sensor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body_temp_frame.sizePolicy().hasHeightForWidth())
        self.body_temp_frame.setSizePolicy(sizePolicy)
        self.body_temp_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.body_temp_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.body_temp_frame.setObjectName("body_temp_frame")
        self.body_temp_layout = QtWidgets.QVBoxLayout(self.body_temp_frame)
        self.body_temp_layout.setObjectName("body_temp_layout")
        self.body_temp_label = QtWidgets.QLabel(self.body_temp_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.body_temp_label.setFont(font)
        self.body_temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.body_temp_label.setObjectName("body_temp_label")
        self.body_temp_layout.addWidget(self.body_temp_label)
        self.body_temp_value = QtWidgets.QLabel(self.body_temp_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.body_temp_value.setFont(font)
        self.body_temp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.body_temp_value.setObjectName("body_temp_value")
        self.body_temp_layout.addWidget(self.body_temp_value)
        self.sensor_layout.addWidget(self.body_temp_frame, 0, 1, 1, 1)
        self.environment_frame = QtWidgets.QFrame(self.sensor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.environment_frame.sizePolicy().hasHeightForWidth())
        self.environment_frame.setSizePolicy(sizePolicy)
        self.environment_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.environment_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.environment_frame.setObjectName("environment_frame")
        self.environment_layout = QtWidgets.QVBoxLayout(self.environment_frame)
        self.environment_layout.setObjectName("environment_layout")
        self.environment_label = QtWidgets.QLabel(self.environment_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.environment_label.setFont(font)
        self.environment_label.setAlignment(QtCore.Qt.AlignCenter)
        self.environment_label.setObjectName("environment_label")
        self.environment_layout.addWidget(self.environment_label)
        self.environment_value = QtWidgets.QLabel(self.environment_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.environment_value.setFont(font)
        self.environment_value.setAlignment(QtCore.Qt.AlignCenter)
        self.environment_value.setObjectName("environment_value")
        self.environment_layout.addWidget(self.environment_value)
        self.sensor_layout.addWidget(self.environment_frame, 2, 0, 1, 1)
        self.blood_pressure_frame = QtWidgets.QFrame(self.sensor_group)
        self.blood_pressure_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.blood_pressure_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blood_pressure_frame.setObjectName("blood_pressure_frame")
        self.blood_pressure_layout = QtWidgets.QVBoxLayout(self.blood_pressure_frame)
        self.blood_pressure_layout.setObjectName("blood_pressure_layout")
        self.blood_pressure_label = QtWidgets.QLabel(self.blood_pressure_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.blood_pressure_label.setFont(font)
        self.blood_pressure_label.setAlignment(QtCore.Qt.AlignCenter)
        self.blood_pressure_label.setObjectName("blood_pressure_label")
        self.blood_pressure_layout.addWidget(self.blood_pressure_label)
        self.blood_pressure_value = QtWidgets.QLabel(self.blood_pressure_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.blood_pressure_value.setFont(font)
        self.blood_pressure_value.setAlignment(QtCore.Qt.AlignCenter)
        self.blood_pressure_value.setObjectName("blood_pressure_value")
        self.blood_pressure_layout.addWidget(self.blood_pressure_value)
        self.sensor_layout.addWidget(self.blood_pressure_frame, 1, 0, 1, 1)
        self.air_quality_frame = QtWidgets.QFrame(self.sensor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.air_quality_frame.sizePolicy().hasHeightForWidth())
        self.air_quality_frame.setSizePolicy(sizePolicy)
        self.air_quality_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.air_quality_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.air_quality_frame.setObjectName("air_quality_frame")
        self.air_quality_layout = QtWidgets.QVBoxLayout(self.air_quality_frame)
        self.air_quality_layout.setObjectName("air_quality_layout")
        self.air_quality_label = QtWidgets.QLabel(self.air_quality_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.air_quality_label.setFont(font)
        self.air_quality_label.setAlignment(QtCore.Qt.AlignCenter)
        self.air_quality_label.setObjectName("air_quality_label")
        self.air_quality_layout.addWidget(self.air_quality_label)
        self.air_quality_value = QtWidgets.QLabel(self.air_quality_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.air_quality_value.setFont(font)
        self.air_quality_value.setAlignment(QtCore.Qt.AlignCenter)
        self.air_quality_value.setObjectName("air_quality_value")
        self.air_quality_layout.addWidget(self.air_quality_value)
        self.sensor_layout.addWidget(self.air_quality_frame, 2, 1, 1, 1)
        self.main_layout.addWidget(self.sensor_group, 1, 0, 1, 1)
        self.config_group = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_group.sizePolicy().hasHeightForWidth())
        self.config_group.setSizePolicy(sizePolicy)
        self.config_group.setStyleSheet("\n"
"        QGroupBox {\n"
"            border: 2px solid #9C27B0;\n"
"            border-radius: 10px;\n"
"            margin-top: 10px;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 5px;\n"
"            font-weight: bold;\n"
"            color: #9C27B0;\n"
"        }\n"
"\n"
"QPushButton {\n"
"  background-color: #04AA6D; /* Green */\n"
"  border: none;\n"
"  color: white;\n"
"\n"
"  text-align: center;\n"
"  text-decoration: none;\n"
"  display: inline-block;\n"
"  font-size: 8px;\n"
"  margin: 4px 2px;\n"
"  transition-duration: 0.4s;\n"
"  cursor: pointer;\n"
"}\n"
"       ")
        self.config_group.setObjectName("config_group")
        self.config_layout = QtWidgets.QVBoxLayout(self.config_group)
        self.config_layout.setObjectName("config_layout")
        self.start_system = QtWidgets.QPushButton(self.config_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_system.sizePolicy().hasHeightForWidth())
        self.start_system.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.start_system.setFont(font)
        self.start_system.setFocusPolicy(QtCore.Qt.NoFocus)
        self.start_system.setStyleSheet("QPushButton {\n"
"  background-color: white; \n"
"  color: black; \n"
"  border: 2px solid #04AA6D;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #04AA6D;\n"
"  color: white;\n"
"}")
        self.start_system.setObjectName("start_system")
        self.config_layout.addWidget(self.start_system)
        self.stop = QtWidgets.QPushButton(self.config_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stop.sizePolicy().hasHeightForWidth())
        self.stop.setSizePolicy(sizePolicy)
        self.stop.setStyleSheet("QPushButton {\n"
"  background-color: white; \n"
"  color: black; \n"
"  border: 2px solid #f44336;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #f44336;\n"
"  color: white;\n"
"}\n"
"")
        self.stop.setObjectName("stop")
        self.config_layout.addWidget(self.stop)
        self.reset = QtWidgets.QPushButton(self.config_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reset.sizePolicy().hasHeightForWidth())
        self.reset.setSizePolicy(sizePolicy)
        self.reset.setStyleSheet("QPushButton {\n"
"  background-color: white; \n"
"  color: black; \n"
"  border: 2px solid #008CBA;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #008CBA;\n"
"  color: white;\n"
"}")
        self.reset.setObjectName("reset")
        self.config_layout.addWidget(self.reset)
        self.users = QtWidgets.QPushButton(self.config_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.users.sizePolicy().hasHeightForWidth())
        self.users.setSizePolicy(sizePolicy)
        self.users.setStyleSheet("QPushButton {\n"
"  background-color: white;\n"
"  color: black;\n"
"  border: 2px solid #e7e7e7;\n"
"}\n"
"\n"
"QPushButton:hover {background-color: #e7e7e7;}")
        self.users.setObjectName("users")
        self.config_layout.addWidget(self.users)
        self.system = QtWidgets.QPushButton(self.config_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.system.sizePolicy().hasHeightForWidth())
        self.system.setSizePolicy(sizePolicy)
        self.system.setStyleSheet("QPushButton {\n"
"  background-color: white;\n"
"  color: black;\n"
"  border: 2px solid #555555;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"  background-color: #555555;\n"
"  color: white;\n"
"}")
        self.system.setObjectName("system")
        self.config_layout.addWidget(self.system)
        self.main_layout.addWidget(self.config_group, 2, 0, 1, 1)
        ModernDashboard.setCentralWidget(self.centralwidget)

        self.retranslateUi(ModernDashboard)
        QtCore.QMetaObject.connectSlotsByName(ModernDashboard)

    def retranslateUi(self, ModernDashboard):
        _translate = QtCore.QCoreApplication.translate
        ModernDashboard.setWindowTitle(_translate("ModernDashboard", "Geriatric Dashboard"))
        ModernDashboard.setStyleSheet(_translate("ModernDashboard", "background-color: #f0f2f5;"))
        self.groupBox.setTitle(_translate("ModernDashboard", "Home Automation"))
        self.label_3.setText(_translate("ModernDashboard", "CPU Usage"))
        self.bombilla_1.setText(_translate("ModernDashboard", "Lightbulb 1"))
        self.cpu_usage.setText(_translate("ModernDashboard", "0.0%"))
        self.bombilla_2.setText(_translate("ModernDashboard", "Lightbulb 2"))
        self.label_6.setText(_translate("ModernDashboard", "RAM Usage"))
        self.purificador.setText(_translate("ModernDashboard", "Purifier"))
        self.bombilla_4.setText(_translate("ModernDashboard", "Lightbulb 4"))
        self.bombilla_3.setText(_translate("ModernDashboard", "Lightbulb 3"))
        self.deshumificador.setText(_translate("ModernDashboard", "Dehumidifier"))
        self.abanico.setText(_translate("ModernDashboard", "Fan"))
        self.ram_usage.setText(_translate("ModernDashboard", "0.0%"))
        self.label_4.setText(_translate("ModernDashboard", "Status"))
        self.clock_status.setText(_translate("ModernDashboard", "Offline"))
        self.label_9.setText(_translate("ModernDashboard", "ESP_02 Status"))
        self.label_8.setText(_translate("ModernDashboard", "ESP_01 Status "))
        self.esp_01_status.setText(_translate("ModernDashboard", "Offline"))
        self.esp_02_status.setText(_translate("ModernDashboard", "Offline"))
        self.camera_group.setStyleSheet(_translate("ModernDashboard", "\n"
"        QGroupBox {\n"
"            border: 2px solid #4CAF50;\n"
"            border-radius: 10px;\n"
"            margin-top: 10px;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 0 5px 0 5px;\n"
"            font-weight: bold;\n"
"            color: #4CAF50;\n"
"        }\n"
"       "))
        self.camera_group.setTitle(_translate("ModernDashboard", "Cameras"))
        self.cam_frame_1.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.label.setText(_translate("ModernDashboard", "camera"))
        self.cam_label_1.setText(_translate("ModernDashboard", "Camera 1"))
        self.cam_frame_2.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.label_2.setText(_translate("ModernDashboard", "camera"))
        self.cam_label_2.setText(_translate("ModernDashboard", "Camera 2"))
        self.alert_group.setStyleSheet(_translate("ModernDashboard", "\n"
"        QGroupBox {\n"
"            border: 2px solid #FF5722;\n"
"            border-radius: 10px;\n"
"            margin-top: 10px;\n"
"        }\n"
"        QGroupBox::title {\n"
"            subcontrol-origin: margin;\n"
"            left: 10px;\n"
"            padding: 0 5px 0 5px;\n"
"            font-weight: bold;\n"
"            color: #FF5722;\n"
"        }\n"
"       "))
        self.alert_group.setTitle(_translate("ModernDashboard", "Alerts"))
        self.alert_list.setStyleSheet(_translate("ModernDashboard", "color: #FF5722;"))
        self.alert_list.setText(_translate("ModernDashboard", "No alerts"))
        self.sensor_group.setTitle(_translate("ModernDashboard", "Sensors"))
        self.system_frame.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.label11.setText(_translate("ModernDashboard", "System Status"))
        self.system_label.setStyleSheet(_translate("ModernDashboard", "color: #555555;"))
        self.system_label.setText(_translate("ModernDashboard", "Offline"))
        self.heart_rate_frame.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.heart_rate_label.setText(_translate("ModernDashboard", "Heart Rate"))
        self.heart_rate_value.setStyleSheet(_translate("ModernDashboard", "color: #555555;"))
        self.heart_rate_value.setText(_translate("ModernDashboard", "-- bpm"))
        self.body_temp_frame.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.body_temp_label.setText(_translate("ModernDashboard", "Body Temperature"))
        self.body_temp_value.setStyleSheet(_translate("ModernDashboard", "color: #555555;"))
        self.body_temp_value.setText(_translate("ModernDashboard", "-- °C"))
        self.environment_frame.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.environment_label.setText(_translate("ModernDashboard", "Environment"))
        self.environment_value.setStyleSheet(_translate("ModernDashboard", "color: #555555;"))
        self.environment_value.setText(_translate("ModernDashboard", "Temp: -- °C\n"
"Humidity: -- %"))
        self.blood_pressure_frame.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.blood_pressure_label.setText(_translate("ModernDashboard", "Blood Pressure"))
        self.blood_pressure_value.setStyleSheet(_translate("ModernDashboard", "color: #555555;"))
        self.blood_pressure_value.setText(_translate("ModernDashboard", "-- / -- mmHg"))
        self.air_quality_frame.setStyleSheet(_translate("ModernDashboard", "background-color: #ffffff; border-radius: 8px;"))
        self.air_quality_label.setText(_translate("ModernDashboard", "Air Quality"))
        self.air_quality_value.setStyleSheet(_translate("ModernDashboard", "color: #555555;"))
        self.air_quality_value.setText(_translate("ModernDashboard", "Good"))
        self.config_group.setTitle(_translate("ModernDashboard", "Configuration"))
        self.start_system.setText(_translate("ModernDashboard", "Start"))
        self.stop.setText(_translate("ModernDashboard", "Stop"))
        self.reset.setText(_translate("ModernDashboard", "Reset"))
        self.users.setText(_translate("ModernDashboard", "..."))
        self.system.setText(_translate("ModernDashboard", "..."))
